### ISSUE TITLE
Tracking issue for finishing WebRTC migration

### ISSUE THREAD

**Issue by poga** [ailabstw/go-pttai-core#12]
This is a tracking issue for replacing libp2p with WebRTC.

We've already finished migrating to WebRTC in #271. 

**Steps:**
- [x] Implement signal server https://github.com/ailabstw/pttai-signal-server
- [x] Switch to pion/webrtc #258 
- [ ] Implement TURN (relay) with upstream

**Related issues:**

none

**Unresolved questions:**

none
